#!/bin/env bash
# Detect a Python intepreter.
python3=$(whereis python3 | awk '{ print $2 }')
python=$(whereis python | awk '{ print $2 }')
pypy3=$(whereis pypy3 | awk '{ print $2 }')
pypy=$(whereis pypy | awk '{print $2 }')

if ! [ -z $python3 ]; then
    echo $python3
    exit 0
fi

if ! [ -z $python ]; then
    echo $python
    exit 0
fi

if ! [ -z $pypy3 ]; then
    echo $pypy3
    exit 0
fi

if ! [ -z $pypy ]; then
    echo $pypy
    exit 0
fi

echo "Error: Cannot find a Python intepreter."
exit -1
