#!/bin/sh
# Run ("run") script for uredis service for runit.
# /etc/sv/uredis/run
lockfile="/var/lock/uredis.lock"

exec 200>"$lockfile"
exec flock -n 200 || exit 0

exec chpst -u redis /usr/local/bin/uredis-service.sh
