#!/bin/sh
# Run ("run") script for uredis service for runit.
# /etc/sv/uredis/run
lockfile="/var/lock/uredis.lock"

exec 200>"$lockfile"
exec flock -n 200 || exit 0

exec chpst -u redis python3 /opt/uredis/uredis-server.pyz -z 15000000000 --daemon-safe --no-pid
