name: Test uredis server and client (uv)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  uv_tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up python
        run: uv python install

      - name: Test the parser
        run: make test_parser

      - name: Run client source checks (uvx mypy)
        run: make check_client

      - name: Run server source checks (uvx mypy)
        run: make check_server
