name: Test uredis server and client (uv)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install

      - name: Install project testing dependencies (uv)
        run: uv pip sync requirements.txt

      - name: Test the parser
        run: make test_parser

      - name: Run source checks (mypy)
        run: make check

